# Generated by Django 4.1.3 on 2022-11-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='image_url',
            field=models.URLField(),
        ),
    ]
