# Generated by Django 4.1.1 on 2022-09-30 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_affiliation_contact_project_skill_projecturl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliation',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='platform_icon',
        ),
        migrations.RemoveField(
            model_name='general',
            name='image',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='icon',
        ),
    ]
