# Generated by Django 4.1.3 on 2022-11-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_general_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='image_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='platform_image_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='projecturl',
            name='url',
            field=models.URLField(),
        ),
    ]
