# Generated by Django 4.1.3 on 2023-04-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_affiliation_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecturl',
            name='url_type',
            field=models.CharField(choices=[('REPO', 'Repository'), ('LINK', 'Link')], default='LINK', max_length=4),
        ),
    ]
