# Generated by Django 4.1.1 on 2022-09-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_remove_affiliation_icon_remove_contact_platform_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliation',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='contact',
            name='platform_image_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='general',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='projecturl',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
