# Generated by Django 4.1.1 on 2022-10-01 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_affiliation_image_url_contact_platform_image_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certification',
            old_name='end_year',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='end_year',
            new_name='end_date',
        ),
    ]
