# Generated by Django 4.1.3 on 2023-04-23 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_projecturl_url_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecturl',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_urls', to='about.project'),
        ),
    ]
