# Generated by Django 4.1.3 on 2023-06-06 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_experience_end_date_experience_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='experience',
            name='affiliation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='about.affiliation'),
        ),
    ]
