# Generated by Django 4.1.3 on 2023-06-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_experience_description_alter_experience_affiliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
