# Generated by Django 4.1.3 on 2024-04-26 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_project_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(to='about.skill'),
        ),
    ]
