# Generated by Django 4.1.3 on 2024-04-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_alter_skill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillcategory',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
