# Generated by Django 4.1.3 on 2024-07-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0012_skillcategory_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateField(default='2023-01-01'),
            preserve_default=False,
        ),
    ]
